version: '3'
services:
  web:
    build: ./web
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - "3306:3306"
