version: '3'
services:
  web:
    build: ./src
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres    
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:      
