# Default
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

# Development
development:
  <<: *default
  database: app_development

# Test
test:
  <<: *default
  database: app_test  

# Production
production:
  <<: *default
  database: app_production
  username: app
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>