# Default
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: db

# Development
development:
  <<: *default
  database: app_development

# Test
test:
  <<: *default
  database: app_test
